# Site setings
name: 'CloudInsights'
description: 'Cloud Solutions Architect and DevOps Engineer'
meta_description: 'Blog about all Clouds and DevOps.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'Pawel_Chylak.png'
  greetings: "Hi!"
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://cloudinsights.blog
# disqus: 'cloudinsights-blog'
# mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: youremail@email.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'pawelchylak'
facebook: 'pchylak'
github: 'pchylak'
linkedin: 'pawel-chylak'

# Navigation
navigation:
  - text: Home
    url: /
#   - text: About
#     url: /about
#   - text: Contact Me
#     url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
